[2025-07-01T14:58:05.248+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: northwind.carregamento_postgres manual__2025-07-01T14:57:27.657423+00:00 [queued]>
[2025-07-01T14:58:05.258+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: northwind.carregamento_postgres manual__2025-07-01T14:57:27.657423+00:00 [queued]>
[2025-07-01T14:58:05.258+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-01T14:58:05.269+0000] {taskinstance.py:2191} INFO - Executing <Task(DockerOperator): carregamento_postgres> on 2025-07-01 14:57:27.657423+00:00
[2025-07-01T14:58:05.276+0000] {standard_task_runner.py:60} INFO - Started process 225 to run task
[2025-07-01T14:58:05.279+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'northwind', 'carregamento_postgres', 'manual__2025-07-01T14:57:27.657423+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/northwind.py', '--cfg-path', '/tmp/tmp74bo60jp']
[2025-07-01T14:58:05.281+0000] {standard_task_runner.py:88} INFO - Job 7: Subtask carregamento_postgres
[2025-07-01T14:58:05.331+0000] {task_command.py:423} INFO - Running <TaskInstance: northwind.carregamento_postgres manual__2025-07-01T14:57:27.657423+00:00 [running]> on host 64e5e3bd5aa6
[2025-07-01T14:58:05.407+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='lrbf@cin.ufpe.br' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='northwind' AIRFLOW_CTX_TASK_ID='carregamento_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-07-01T14:57:27.657423+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-01T14:57:27.657423+00:00'
[2025-07-01T14:58:05.460+0000] {docker.py:359} INFO - Starting docker container from image meltano:latest
[2025-07-01T14:58:05.745+0000] {docker.py:429} INFO - Running meltano install...
[2025-07-01T14:58:06.960+0000] {docker.py:429} INFO - [2m2025-07-01T14:58:06.959978Z[0m [[32m[1minfo     [0m] [1mInstalling 7 plugins          [0m
[2025-07-01T14:58:06.973+0000] {docker.py:429} INFO - [2m2025-07-01T14:58:06.972672Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-postgres'[0m
[2025-07-01T14:58:06.993+0000] {docker.py:429} INFO - [2m2025-07-01T14:58:06.992906Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-csv'[0m
[2025-07-01T14:58:07.013+0000] {docker.py:429} INFO - [2m2025-07-01T14:58:07.012441Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-csv-latest'[0m
[2025-07-01T14:58:07.032+0000] {docker.py:429} INFO - [2m2025-07-01T14:58:07.031853Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-postgres'[0m
[2025-07-01T14:58:07.053+0000] {docker.py:429} INFO - [2m2025-07-01T14:58:07.052795Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-csv'[0m
[2025-07-01T14:58:07.075+0000] {docker.py:429} INFO - [2m2025-07-01T14:58:07.074512Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-csv-postgres'[0m
[2025-07-01T14:58:07.107+0000] {docker.py:429} INFO - [2m2025-07-01T14:58:07.106961Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-csv-csv'[0m
[2025-07-01T14:58:07.544+0000] {docker.py:429} INFO - [2m2025-07-01T14:58:07.543173Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-postgres'[0m
[2025-07-01T14:58:07.603+0000] {docker.py:429} INFO - [2m2025-07-01T14:58:07.602463Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-postgres'[0m
[2025-07-01T14:58:11.347+0000] {docker.py:429} INFO - [2m2025-07-01T14:58:11.347145Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-csv-latest'[0m
[2025-07-01T14:58:11.856+0000] {docker.py:429} INFO - [2m2025-07-01T14:58:11.855650Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-csv' [0m
[2025-07-01T14:58:12.073+0000] {docker.py:429} INFO - [2m2025-07-01T14:58:12.073164Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-csv-csv'[0m
[2025-07-01T14:58:12.135+0000] {docker.py:429} INFO - [2m2025-07-01T14:58:12.135170Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-csv-postgres'[0m
[2025-07-01T14:58:12.301+0000] {docker.py:429} INFO - [2m2025-07-01T14:58:12.300676Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-csv' [0m
[2025-07-01T14:58:12.301+0000] {docker.py:429} INFO - [2m2025-07-01T14:58:12.301002Z[0m [[32m[1minfo     [0m] [1mInstalled 7/7 plugins         [0m
[2025-07-01T14:58:12.632+0000] {docker.py:429} INFO - Meltano install completed. Executing command: meltano el tap-csv-latest target-postgres
[2025-07-01T14:58:13.584+0000] {docker.py:429} INFO - [2m2025-07-01T14:58:13.583925Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2025-07-01T14:58:13.909+0000] {docker.py:429} INFO - [2m2025-07-01T14:58:13.908972Z[0m [[32m[1minfo     [0m] [1mRunning extract & load...     [0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35m1b8b5714-d57e-468a-95cc-76d73dd4c01c[0m [36mstate_id[0m=[35m2025-07-01T145813--tap-csv-latest--target-postgres[0m
[2025-07-01T14:58:14.733+0000] {docker.py:429} INFO - [2m2025-07-01T14:58:14.732680Z[0m [[32m[1minfo     [0m] [1mNo CSV file definitions found.[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m1b8b5714-d57e-468a-95cc-76d73dd4c01c[0m [36mstate_id[0m=[35m2025-07-01T145813--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T14:58:14.889+0000] {docker.py:429} INFO - [2m2025-07-01T14:58:14.888290Z[0m [[32m[1minfo     [0m] [1mtarget-postgres v0.4.3, Meltano SDK v0.47.4[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1b8b5714-d57e-468a-95cc-76d73dd4c01c[0m [36mstate_id[0m=[35m2025-07-01T145813--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T14:58:14.890+0000] {docker.py:429} INFO - [2m2025-07-01T14:58:14.889782Z[0m [[32m[1minfo     [0m] [1m/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/plugin_base.py:715: SingerSDKDeprecationWarning: Passing a list of config file paths is deprecated. Please pass the config as a dictionary instead.[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1b8b5714-d57e-468a-95cc-76d73dd4c01c[0m [36mstate_id[0m=[35m2025-07-01T145813--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-01T14:58:14.890067Z[0m [[32m[1minfo     [0m] [1m  super().__init__(           [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1b8b5714-d57e-468a-95cc-76d73dd4c01c[0m [36mstate_id[0m=[35m2025-07-01T145813--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T14:58:14.890+0000] {docker.py:429} INFO - [2m2025-07-01T14:58:14.890204Z[0m [[32m[1minfo     [0m] [1m                              [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1b8b5714-d57e-468a-95cc-76d73dd4c01c[0m [36mstate_id[0m=[35m2025-07-01T145813--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T14:58:14.891+0000] {docker.py:429} INFO - [2m2025-07-01T14:58:14.890383Z[0m [[32m[1minfo     [0m] [1mSkipping parse of env var settings...[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1b8b5714-d57e-468a-95cc-76d73dd4c01c[0m [36mstate_id[0m=[35m2025-07-01T145813--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T14:58:14.891+0000] {docker.py:429} INFO - [2m2025-07-01T14:58:14.890635Z[0m [[32m[1minfo     [0m] [1mThe `dialect+driver` configuration option is deprecated. Please set it to `postgresql+psycopg`, as this will be the hard-coded value in the future.[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1b8b5714-d57e-468a-95cc-76d73dd4c01c[0m [36mstate_id[0m=[35m2025-07-01T145813--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T14:58:14.891+0000] {docker.py:429} INFO - [2m2025-07-01T14:58:14.890852Z[0m [[32m[1minfo     [0m] [1mReader 'target-postgres' completed processing 0 lines of input (0 schemas, 0 records, 0 batch manifests, 0 state messages, 0 activate version messages).[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m1b8b5714-d57e-468a-95cc-76d73dd4c01c[0m [36mstate_id[0m=[35m2025-07-01T145813--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T14:58:14.962+0000] {docker.py:429} INFO - [2m2025-07-01T14:58:14.961280Z[0m [[31m[1merror    [0m] [1mExtraction failed             [0m [36mcode[0m=[35m1[0m [36mmessage[0m=[35m'No CSV file definitions found.'[0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35m1b8b5714-d57e-468a-95cc-76d73dd4c01c[0m [36mstate_id[0m=[35m2025-07-01T145813--tap-csv-latest--target-postgres[0m
[2025-07-01T14:58:14.962+0000] {docker.py:429} INFO - [2m2025-07-01T14:58:14.961907Z[0m [[32m[1minfo     [0m] [1mELT could not be completed: Extractor failed.[0m [36mcmd_type[0m=[35melt[0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35m1b8b5714-d57e-468a-95cc-76d73dd4c01c[0m [36mstate_id[0m=[35m2025-07-01T145813--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T14:58:14.962+0000] {docker.py:429} INFO - [2m2025-07-01T14:58:14.962157Z[0m [[32m[1minfo     [0m] [1mFor more detailed log messages re-run the command using 'meltano --log-level=debug ...' CLI flag.[0m [36mcmd_type[0m=[35melt[0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35m1b8b5714-d57e-468a-95cc-76d73dd4c01c[0m [36mstate_id[0m=[35m2025-07-01T145813--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T14:58:14.963+0000] {docker.py:429} INFO - [2m2025-07-01T14:58:14.962347Z[0m [[32m[1minfo     [0m] [1mNote that you can also check the generated log file at '/opt/meltano/.meltano/logs/elt/2025-07-01T145813--tap-csv-latest--target-postgres/1b8b5714-d57e-468a-95cc-76d73dd4c01c/elt.log'.[0m [36mcmd_type[0m=[35melt[0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35m1b8b5714-d57e-468a-95cc-76d73dd4c01c[0m [36mstate_id[0m=[35m2025-07-01T145813--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T14:58:14.963+0000] {docker.py:429} INFO - [2m2025-07-01T14:58:14.962516Z[0m [[32m[1minfo     [0m] [1mFor more information on debugging and logging: https://docs.meltano.com/reference/command-line-interface#debugging[0m [36mcmd_type[0m=[35melt[0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35m1b8b5714-d57e-468a-95cc-76d73dd4c01c[0m [36mstate_id[0m=[35m2025-07-01T145813--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-01T14:58:14.974+0000] {docker.py:429} INFO - Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to
join our friendly Slack community.

ELT could not be completed: Extractor failed.
For more detailed log messages re-run the command using 'meltano --log-level=debug ...' CLI flag.
Note that you can also check the generated log file at '/opt/meltano/.meltano/logs/elt/2025-07-01T145813--tap-csv-latest--target-postgres/1b8b5714-d57e-468a-95cc-76d73dd4c01c/elt.log'.
For more information on debugging and logging: https://docs.meltano.com/reference/command-line-interface#debugging
[2025-07-01T14:58:15.998+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 502, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 376, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 437, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-07-01T14:58:16.001+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=northwind, task_id=carregamento_postgres, execution_date=20250701T145727, start_date=20250701T145805, end_date=20250701T145816
[2025-07-01T14:58:16.014+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 7 for task carregamento_postgres (Docker container failed: {'StatusCode': 1}; 225)
[2025-07-01T14:58:16.057+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-01T14:58:16.075+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
