[2025-07-09T20:51:39.011+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: northwind.carregamento_postgres manual__2025-07-09T20:45:38.869934+00:00 [queued]>
[2025-07-09T20:51:39.022+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: northwind.carregamento_postgres manual__2025-07-09T20:45:38.869934+00:00 [queued]>
[2025-07-09T20:51:39.023+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-07-09T20:51:39.037+0000] {taskinstance.py:2191} INFO - Executing <Task(DockerOperator): carregamento_postgres> on 2025-07-09 20:45:38.869934+00:00
[2025-07-09T20:51:39.044+0000] {standard_task_runner.py:60} INFO - Started process 213 to run task
[2025-07-09T20:51:39.050+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'northwind', 'carregamento_postgres', 'manual__2025-07-09T20:45:38.869934+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/northwind.py', '--cfg-path', '/tmp/tmp4rsjrtej']
[2025-07-09T20:51:39.053+0000] {standard_task_runner.py:88} INFO - Job 97: Subtask carregamento_postgres
[2025-07-09T20:51:39.138+0000] {task_command.py:423} INFO - Running <TaskInstance: northwind.carregamento_postgres manual__2025-07-09T20:45:38.869934+00:00 [running]> on host 9d65785a077b
[2025-07-09T20:51:39.242+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='lrbf@cin.ufpe.br' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='northwind' AIRFLOW_CTX_TASK_ID='carregamento_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-07-09T20:45:38.869934+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-09T20:45:38.869934+00:00'
[2025-07-09T20:51:39.320+0000] {docker.py:359} INFO - Starting docker container from image meltano:latest
[2025-07-09T20:51:39.735+0000] {docker.py:429} INFO - Running meltano install...
[2025-07-09T20:51:41.492+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:41.492041Z[0m [[32m[1minfo     [0m] [1mInstalling 7 plugins          [0m
[2025-07-09T20:51:41.506+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:41.505552Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-postgres'[0m
[2025-07-09T20:51:41.533+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:41.532647Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-csv'[0m
[2025-07-09T20:51:41.571+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:41.570820Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-csv-latest'[0m
[2025-07-09T20:51:41.608+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:41.607095Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-postgres'[0m
[2025-07-09T20:51:41.649+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:41.648514Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-csv'[0m
[2025-07-09T20:51:41.698+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:41.697250Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-csv-postgres'[0m
[2025-07-09T20:51:41.754+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:41.753123Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-csv-csv'[0m
[2025-07-09T20:51:44.601+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:44.586666Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-postgres'[0m
[2025-07-09T20:51:44.617+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:44.604567Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-postgres'[0m
[2025-07-09T20:51:49.208+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:49.207983Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-csv-latest'[0m
[2025-07-09T20:51:49.229+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:49.228760Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-csv' [0m
[2025-07-09T20:51:49.938+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:49.937116Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-csv' [0m
[2025-07-09T20:51:50.055+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:50.054951Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-csv-postgres'[0m
[2025-07-09T20:51:50.160+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:50.159664Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-csv-csv'[0m
[2025-07-09T20:51:50.160+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:50.160465Z[0m [[32m[1minfo     [0m] [1mInstalled 7/7 plugins         [0m
[2025-07-09T20:51:51.557+0000] {docker.py:429} INFO - Meltano install completed. Executing command: bash -c meltano config tap-csv-latest set csv_files_definition /opt/meltano/config/tap-csv-latest.json && meltano el tap-csv-latest target-postgres
[2025-07-09T20:51:52.795+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:52.794706Z[0m [[32m[1minfo     [0m] [1mThe default environment 'dev' will be ignored for `meltano config`. To configure a specific environment, please use the option `--environment=<environment name>`.[0m
[2025-07-09T20:51:52.999+0000] {docker.py:429} INFO - Extractor 'tap-csv-latest' setting 'csv_files_definition' was set in `meltano.yml`: '/opt/meltano/config/tap-csv-latest.json'
[2025-07-09T20:51:55.039+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:55.038390Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2025-07-09T20:51:55.411+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:55.410917Z[0m [[32m[1minfo     [0m] [1mRunning extract & load...     [0m [36mname[0m=[35mmeltano[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m
[2025-07-09T20:51:53.573+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.572056Z[0m [[32m[1minfo     [0m] [1mBeginning full_table sync of 'order_details'...[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.574+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.572570Z[0m [[32m[1minfo     [0m] [1mTap has custom mapper. Using 1 provided map(s).[0m [36mcmd_type[0m=[35mextractor[0m [36mname[0m=[35mtap-csv-latest[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.710+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.709755Z[0m [[32m[1minfo     [0m] [1mtarget-postgres v0.4.3, Meltano SDK v0.47.4[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.711+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.710880Z[0m [[32m[1minfo     [0m] [1m/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/plugin_base.py:715: SingerSDKDeprecationWarning: Passing a list of config file paths is deprecated. Please pass the config as a dictionary instead.[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.712+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.711246Z[0m [[32m[1minfo     [0m] [1m  super().__init__(           [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.713+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.711531Z[0m [[32m[1minfo     [0m] [1m                              [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.713+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.712017Z[0m [[32m[1minfo     [0m] [1mSkipping parse of env var settings...[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.855+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.854679Z[0m [[32m[1minfo     [0m] [1mTraceback (most recent call last):[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.855+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.855002Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 145, in __init__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.856+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.855406Z[0m [[32m[1minfo     [0m] [1m    self._dbapi_connection = engine.raw_connection()[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.856+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.855585Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3297, in raw_connection[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.857+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.856489Z[0m [[32m[1minfo     [0m] [1m    return self.pool.connect()[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.857+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.856925Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 449, in connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.858+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.857459Z[0m [[32m[1minfo     [0m] [1m    return _ConnectionFairy._checkout(self)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.858+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.857863Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 1264, in _checkout[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.859+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.858418Z[0m [[32m[1minfo     [0m] [1m    fairy = _ConnectionRecord.checkout(pool)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.859+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.858946Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 713, in checkout[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.859+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.859387Z[0m [[32m[1minfo     [0m] [1m    rec = pool._do_get()      [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.860+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.859743Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 180, in _do_get[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.860+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.860098Z[0m [[32m[1minfo     [0m] [1m    self._dec_overflow()      [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.861+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.860550Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.863+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.860875Z[0m [[32m[1minfo     [0m] [1m    raise exc_value.with_traceback(exc_tb)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T20:51:53.861130Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T20:51:53.861389Z[0m [[32m[1minfo     [0m] [1m    return self._create_connection()[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T20:51:53.861589Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T20:51:53.861852Z[0m [[32m[1minfo     [0m] [1m    return _ConnectionRecord(self)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T20:51:53.862038Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 675, in __init__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T20:51:53.862214Z[0m [[32m[1minfo     [0m] [1m    self.__connect()          [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T20:51:53.862390Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 902, in __connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T20:51:53.862577Z[0m [[32m[1minfo     [0m] [1m    pool.logger.debug("Error on connect(): %s", e)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T20:51:53.862784Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.864+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.863110Z[0m [[32m[1minfo     [0m] [1m    raise exc_value.with_traceback(exc_tb)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.864+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.863395Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 897, in __connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.864+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.863694Z[0m [[32m[1minfo     [0m] [1m    self.dbapi_connection = connection = pool._invoke_creator(self)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.865+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.863968Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 646, in connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.865+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.864275Z[0m [[32m[1minfo     [0m] [1m    return dialect.connect(*cargs, **cparams)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.865+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.864632Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 625, in connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.866+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.865191Z[0m [[32m[1minfo     [0m] [1m    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.866+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.865818Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/psycopg/connection.py", line 125, in connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.867+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.866643Z[0m [[32m[1minfo     [0m] [1m    raise type(last_ex)("\n".join(lines)).with_traceback(None)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.869+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.867780Z[0m [[32m[1minfo     [0m] [1mpsycopg.OperationalError: connection failed: connection to server at "127.0.0.1", port 5432 failed: Connection refused[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.870+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.869069Z[0m [[32m[1minfo     [0m] [1m	Is the server running on that host and accepting TCP/IP connections?[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.871+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.870410Z[0m [[32m[1minfo     [0m] [1mMultiple connection attempts failed. All failures were:[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.871+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.871038Z[0m [[32m[1minfo     [0m] [1m- host: 'localhost', port: 5432, hostaddr: '::1': connection failed: connection to server at "::1", port 5432 failed: Connection refused[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.872+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.871730Z[0m [[32m[1minfo     [0m] [1m	Is the server running on that host and accepting TCP/IP connections?[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.872+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.872231Z[0m [[32m[1minfo     [0m] [1m- host: 'localhost', port: 5432, hostaddr: '127.0.0.1': connection failed: connection to server at "127.0.0.1", port 5432 failed: Connection refused[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.873+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.872725Z[0m [[32m[1minfo     [0m] [1m	Is the server running on that host and accepting TCP/IP connections?[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.873+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.873253Z[0m [[32m[1minfo     [0m] [1m                              [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.874+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.873614Z[0m [[32m[1minfo     [0m] [1mThe above exception was the direct cause of the following exception:[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.874+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.873972Z[0m [[32m[1minfo     [0m] [1m                              [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.875+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.874356Z[0m [[32m[1minfo     [0m] [1mTraceback (most recent call last):[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.875+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.874738Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/bin/target-postgres", line 8, in <module>[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.876+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.875163Z[0m [[32m[1minfo     [0m] [1m    sys.exit(TargetPostgres.cli())[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.876+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.875561Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/click/core.py", line 1161, in __call__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.876+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.875962Z[0m [[32m[1minfo     [0m] [1m    return self.main(*args, **kwargs)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.877+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.876359Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/click/core.py", line 1082, in main[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.877+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.876746Z[0m [[32m[1minfo     [0m] [1m    rv = self.invoke(ctx)     [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.877+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.877099Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/plugin_base.py", line 98, in invoke[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.878+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.877446Z[0m [[32m[1minfo     [0m] [1m    return super().invoke(ctx)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.878+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.877803Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/click/core.py", line 1443, in invoke[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.878+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.878158Z[0m [[32m[1minfo     [0m] [1m    return ctx.invoke(self.callback, **ctx.params)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.879+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.878473Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/click/core.py", line 788, in invoke[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.880+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.879291Z[0m [[32m[1minfo     [0m] [1m    return __callback(*args, **kwargs)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.880+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.879834Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/target_base.py", line 588, in invoke[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.880+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.880227Z[0m [[32m[1minfo     [0m] [1m    target.listen(file_input) [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.881+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.880710Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/plugin_base.py", line 775, in listen[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.881+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.881203Z[0m [[32m[1minfo     [0m] [1m    counter = self.process_lines(file_input)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.882+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.881615Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/plugin_base.py", line 801, in process_lines[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.882+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.882005Z[0m [[32m[1minfo     [0m] [1m    return self.message_reader.process_lines([0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.883+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.882383Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/singerlib/encoding/base.py", line 70, in process_lines[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.883+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.882752Z[0m [[32m[1minfo     [0m] [1m    callback(line_dict)       [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.884+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.883408Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/target_base.py", line 403, in _process_schema_message[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.884+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.883864Z[0m [[32m[1minfo     [0m] [1m    _ = self.get_sink(        [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.885+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.884785Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/target_base.py", line 817, in get_sink[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.886+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.885203Z[0m [[32m[1minfo     [0m] [1m    return self.add_sqlsink(stream_name, schema, key_properties)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.888+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.887417Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/target_base.py", line 751, in add_sqlsink[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.888+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.888093Z[0m [[32m[1minfo     [0m] [1m    sink.setup()              [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.889+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.888891Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/target_postgres/sinks.py", line 58, in setup[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.890+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.889325Z[0m [[32m[1minfo     [0m] [1m    self.connector.prepare_schema(self.schema_name)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.890+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.889990Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/connectors/sql.py", line 1367, in prepare_schema[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.891+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.890539Z[0m [[32m[1minfo     [0m] [1m    if not self.schema_exists(schema_name):[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.892+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.891010Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/singer_sdk/connectors/sql.py", line 1200, in schema_exists[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.892+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.891608Z[0m [[32m[1minfo     [0m] [1m    schemas = set(sa.inspect(self._engine).get_schema_names())[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.893+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.892052Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/inspection.py", line 140, in inspect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.893+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.892438Z[0m [[32m[1minfo     [0m] [1m    ret = reg(subject)        [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.893+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.892795Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 313, in _engine_insp[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.894+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.893152Z[0m [[32m[1minfo     [0m] [1m    return Inspector._construct(Inspector._init_engine, bind)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.894+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.893582Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 246, in _construct[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.894+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.893955Z[0m [[32m[1minfo     [0m] [1m    init(self, bind)          [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.895+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.894323Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 257, in _init_engine[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.895+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.894650Z[0m [[32m[1minfo     [0m] [1m    engine.connect().close()  [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.895+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.895033Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3273, in connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.896+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.895399Z[0m [[32m[1minfo     [0m] [1m    return self._connection_cls(self)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.896+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.895771Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 147, in __init__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.896+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.896130Z[0m [[32m[1minfo     [0m] [1m    Connection._handle_dbapi_exception_noconnection([0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.897+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.896568Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2436, in _handle_dbapi_exception_noconnection[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.897+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.896944Z[0m [[32m[1minfo     [0m] [1m    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.897+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.897267Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 145, in __init__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.898+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.897629Z[0m [[32m[1minfo     [0m] [1m    self._dbapi_connection = engine.raw_connection()[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.898+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.898029Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3297, in raw_connection[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.899+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.898389Z[0m [[32m[1minfo     [0m] [1m    return self.pool.connect()[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.899+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.898750Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 449, in connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.900+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.899465Z[0m [[32m[1minfo     [0m] [1m    return _ConnectionFairy._checkout(self)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.900+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.899938Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 1264, in _checkout[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.901+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.900489Z[0m [[32m[1minfo     [0m] [1m    fairy = _ConnectionRecord.checkout(pool)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.901+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.900937Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 713, in checkout[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.902+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.901294Z[0m [[32m[1minfo     [0m] [1m    rec = pool._do_get()      [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.903+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.902463Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 180, in _do_get[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.903+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.902948Z[0m [[32m[1minfo     [0m] [1m    self._dec_overflow()      [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.904+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.903279Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.906+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.903916Z[0m [[32m[1minfo     [0m] [1m    raise exc_value.with_traceback(exc_tb)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T20:51:53.904383Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2m2025-07-09T20:51:53.905164Z[0m [[32m[1minfo     [0m] [1m    return self._create_connection()[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.907+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.906131Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.908+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.906821Z[0m [[32m[1minfo     [0m] [1m    return _ConnectionRecord(self)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.909+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.907303Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 675, in __init__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.909+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.907682Z[0m [[32m[1minfo     [0m] [1m    self.__connect()          [0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.910+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.908064Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 902, in __connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.910+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.908530Z[0m [[32m[1minfo     [0m] [1m    pool.logger.debug("Error on connect(): %s", e)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.911+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.908900Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.911+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.909339Z[0m [[32m[1minfo     [0m] [1m    raise exc_value.with_traceback(exc_tb)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.912+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.909818Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 897, in __connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.913+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.910287Z[0m [[32m[1minfo     [0m] [1m    self.dbapi_connection = connection = pool._invoke_creator(self)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.913+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.910775Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 646, in connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.914+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.911181Z[0m [[32m[1minfo     [0m] [1m    return dialect.connect(*cargs, **cparams)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.914+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.911632Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 625, in connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.915+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.912096Z[0m [[32m[1minfo     [0m] [1m    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.915+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.912521Z[0m [[32m[1minfo     [0m] [1m  File "/opt/meltano/.meltano/loaders/target-postgres/venv/lib/python3.9/site-packages/psycopg/connection.py", line 125, in connect[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.915+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.912990Z[0m [[32m[1minfo     [0m] [1m    raise type(last_ex)("\n".join(lines)).with_traceback(None)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.916+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.913366Z[0m [[32m[1minfo     [0m] [1msqlalchemy.exc.OperationalError: (psycopg.OperationalError) connection failed: connection to server at "127.0.0.1", port 5432 failed: Connection refused[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.916+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.913746Z[0m [[32m[1minfo     [0m] [1m	Is the server running on that host and accepting TCP/IP connections?[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.917+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.914102Z[0m [[32m[1minfo     [0m] [1mMultiple connection attempts failed. All failures were:[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.917+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.914439Z[0m [[32m[1minfo     [0m] [1m- host: 'localhost', port: 5432, hostaddr: '::1': connection failed: connection to server at "::1", port 5432 failed: Connection refused[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.917+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.914761Z[0m [[32m[1minfo     [0m] [1m	Is the server running on that host and accepting TCP/IP connections?[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.917+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.915138Z[0m [[32m[1minfo     [0m] [1m- host: 'localhost', port: 5432, hostaddr: '127.0.0.1': connection failed: connection to server at "127.0.0.1", port 5432 failed: Connection refused[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.918+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.915472Z[0m [[32m[1minfo     [0m] [1m	Is the server running on that host and accepting TCP/IP connections?[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:53.918+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:53.915789Z[0m [[32m[1minfo     [0m] [1m(Background on this error at: https://sqlalche.me/e/20/e3q8)[0m [36mcmd_type[0m=[35mloader[0m [36mname[0m=[35mtarget-postgres[0m [36mrun_id[0m=[35m90b7ae99-1f1a-4637-ba8f-d0d068e828b6[0m [36mstate_id[0m=[35m2025-07-09T205155--tap-csv-latest--target-postgres[0m [36mstdio[0m=[35mstderr[0m
[2025-07-09T20:51:54.383+0000] {docker.py:429} INFO - [2m2025-07-09T20:51:54.013617Z[0m [[31m[1merror    [0m] [1m                              [0m
[31m╭─[0m[31m────────────────────[0m[31m [0m[1;31mTraceback [0m[1;2;31m(most recent call last)[0m[31m [0m[31m─────────────────────[0m[31m─╮[0m
[31m│[0m [2m/venv/lib/python3.9/site-packages/meltano/core/logging/[0m[1moutput_logger.py[0m:217  [31m│[0m
[31m│[0m in redirect_logging                                                          [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m214 [0m[2m│   │   │   [0m*ignore_errors,                                            [31m│[0m
[31m│[0m   [2m215 [0m[2m│   │   [0m)                                                              [31m│[0m
[31m│[0m   [2m216 [0m[2m│   │   [0m[94mtry[0m:                                                           [31m│[0m
[31m│[0m [31m❱ [0m217 [2m│   │   │   [0m[94myield[0m                                                      [31m│[0m
[31m│[0m   [2m218 [0m[2m│   │   [0m[94mexcept[0m ignored_errors:                                         [31m│[0m
[31m│[0m   [2m219 [0m[2m│   │   │   [0m[94mraise[0m                                                      [31m│[0m
[31m│[0m   [2m220 [0m[2m│   │   [0m[94mexcept[0m RunnerError [94mas[0m err:                                     [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/venv/lib/python3.9/site-packages/meltano/cli/[0m[1melt.py[0m:475 in _redirect_output [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m472 [0m[2m│   [0m[94mwith[0m meltano_stdout.redirect_logging(ignore_errors=(CliError,)):   [31m│[0m
[31m│[0m   [2m473 [0m[2m│   │   [0m[94masync[0m [94mwith[0m meltano_stdout.redirect_stdout(), meltano_stderr.re [31m│[0m
[31m│[0m   [2m474 [0m[2m│   │   │   [0m[94mtry[0m:                                                       [31m│[0m
[31m│[0m [31m❱ [0m475 [2m│   │   │   │   [0m[94myield[0m                                                  [31m│[0m
[31m│[0m   [2m476 [0m[2m│   │   │   [0m[94mexcept[0m CliError [94mas[0m err:                                    [31m│[0m
[31m│[0m   [2m477 [0m[2m│   │   │   │   [0merr.print()                                            [31m│[0m
[31m│[0m   [2m478 [0m[2m│   │   │   │   [0m[94mraise[0m                                                  [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/venv/lib/python3.9/site-packages/meltano/cli/[0m[1melt.py[0m:508 in _run_elt         [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m505 [0m[2m│   │   │   [0m[94mif[0m elt_context.only_transform:                             [31m│[0m
[31m│[0m   [2m506 [0m[2m│   │   │   │   [0mlog.info([33m"[0m[33mExtract & load skipped.[0m[33m"[0m)                    [31m│[0m
[31m│[0m   [2m507 [0m[2m│   │   │   [0m[94melse[0m:                                                      [31m│[0m
[31m│[0m [31m❱ [0m508 [2m│   │   │   │   [0m[94mawait[0m _run_extract_load(log, elt_context, output_logge [31m│[0m
[31m│[0m   [2m509 [0m[2m│   │   │   [0m                                                           [31m│[0m
[31m│[0m   [2m510 [0m[2m│   │   │   [0m[94mif[0m elt_context.transformer:                                [31m│[0m
[31m│[0m   [2m511 [0m[2m│   │   │   │   [0mlog.warning(                                           [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/venv/lib/python3.9/site-packages/meltano/cli/[0m[1melt.py[0m:581 in                  [31m│[0m
[31m│[0m _run_extract_load                                                            [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m578 [0m[2m│   │   │   [0m[94mwith[0m loader_log.line_writer() [94mas[0m loader_log_writer:        [31m│[0m
[31m│[0m   [2m579 [0m[2m│   │   │   │   [0m[94mwith[0m extractor_out_writer_ctxmgr() [94mas[0m extractor_out_wr [31m│[0m
[31m│[0m   [2m580 [0m[2m│   │   │   │   │   [0m[94mwith[0m loader_out_writer_ctxmgr() [94mas[0m loader_out_writ [31m│[0m
[31m│[0m [31m❱ [0m581 [2m│   │   │   │   │   │   [0m[94mawait[0m singer_runner.run(                       [31m│[0m
[31m│[0m   [2m582 [0m[2m│   │   │   │   │   │   │   [0m**kwargs,                                  [31m│[0m
[31m│[0m   [2m583 [0m[2m│   │   │   │   │   │   │   [0mextractor_log=extractor_log_writer,        [31m│[0m
[31m│[0m   [2m584 [0m[2m│   │   │   │   │   │   │   [0mloader_log=loader_log_writer,              [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/venv/lib/python3.9/site-packages/meltano/core/runner/[0m[1msinger.py[0m:229 in run   [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m226 [0m[2m│   │   │   [0mtap.prepared([96mself[0m.context.session),                        [31m│[0m
[31m│[0m   [2m227 [0m[2m│   │   │   [0mtarget.prepared([96mself[0m.context.session),                     [31m│[0m
[31m│[0m   [2m228 [0m[2m│   │   [0m):                                                             [31m│[0m
[31m│[0m [31m❱ [0m229 [2m│   │   │   [0m[94mawait[0m [96mself[0m.invoke(  [2m# noqa: RET503[0m                         [31m│[0m
[31m│[0m   [2m230 [0m[2m│   │   │   │   [0mtap,                                                   [31m│[0m
[31m│[0m   [2m231 [0m[2m│   │   │   │   [0mtarget,                                                [31m│[0m
[31m│[0m   [2m232 [0m[2m│   │   │   │   [0mextractor_log=extractor_log,                           [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/venv/lib/python3.9/site-packages/meltano/core/runner/[0m[1msinger.py[0m:148 in       [31m│[0m
[31m│[0m invoke                                                                       [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m145 [0m[2m│   │   │   │   │   [0m)                                                  [31m│[0m
[31m│[0m   [2m146 [0m[2m│   │   │   │   [0m                                                       [31m│[0m
[31m│[0m   [2m147 [0m[2m│   │   │   │   [0mfailed_future = output_futures_failed.pop()            [31m│[0m
[31m│[0m [31m❱ [0m148 [2m│   │   │   │   [0m[94mraise[0m failed_future.exception()                        [31m│[0m
[31m│[0m   [2m149 [0m[2m│   │   │   [0m                                                           [31m│[0m
[31m│[0m   [2m150 [0m[2m│   │   │   [0m[2m# If all of the output handlers completed without raising [0m [31m│[0m
[31m│[0m   [2m151 [0m[2m│   │   │   [0m[2m# exception, we still need to wait for the tap or target t[0m [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/venv/lib/python3.9/site-packages/meltano/core/logging/[0m[1mutils.py[0m:305 in       [31m│[0m
[31m│[0m capture_subprocess_output                                                    [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m302 [0m[2m│   │   │   [0m[94mcontinue[0m                                                   [31m│[0m
[31m│[0m   [2m303 [0m[2m│   │   [0m                                                               [31m│[0m
[31m│[0m   [2m304 [0m[2m│   │   [0m[94mfor[0m writer [95min[0m line_writers:                                    [31m│[0m
[31m│[0m [31m❱ [0m305 [2m│   │   │   [0m[94mif[0m [95mnot[0m [94mawait[0m _write_line_writer(writer, line):             [31m│[0m
[31m│[0m   [2m306 [0m[2m│   │   │   │   [0m[2m# If the destination stream is closed, we can stop cap[0m [31m│[0m
[31m│[0m   [2m307 [0m[2m│   │   │   │   [0m[94mreturn[0m                                                 [31m│[0m
[31m│[0m   [2m308 [0m                                                                       [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/venv/lib/python3.9/site-packages/meltano/core/logging/[0m[1mutils.py[0m:273 in       [31m│[0m
[31m│[0m _write_line_writer                                                           [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m270 [0m[2m│   │   │   [0mwriter.write(line)                                         [31m│[0m
[31m│[0m   [2m271 [0m[2m│   │   │   [0m[94mawait[0m writer.drain()                                       [31m│[0m
[31m│[0m   [2m272 [0m[2m│   │   [0m[94mexcept[0m ([96mBrokenPipeError[0m, [96mConnectionResetError[0m):                [31m│[0m
[31m│[0m [31m❱ [0m273 [2m│   │   │   [0m[94mawait[0m writer.wait_closed()                                 [31m│[0m
[31m│[0m   [2m274 [0m[2m│   │   │   [0m[94mreturn[0m [94mFalse[0m                                               [31m│[0m
[31m│[0m   [2m275 [0m[2m│   [0m[94melse[0m:                                                              [31m│[0m
[31m│[0m   [2m276 [0m[2m│   │   [0mwriter.writeline(line.decode(errors=[33m"[0m[33mreplace[0m[33m"[0m))                [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/usr/local/lib/python3.9/asyncio/[0m[1mstreams.py[0m:359 in wait_closed               [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m356 [0m[2m│   │   [0m[94mreturn[0m [96mself[0m._transport.is_closing()                            [31m│[0m
[31m│[0m   [2m357 [0m[2m│   [0m                                                                   [31m│[0m
[31m│[0m   [2m358 [0m[2m│   [0m[94masync[0m [94mdef[0m[90m [0m[92mwait_closed[0m([96mself[0m):                                       [31m│[0m
[31m│[0m [31m❱ [0m359 [2m│   │   [0m[94mawait[0m [96mself[0m._protocol._get_close_waiter([96mself[0m)                   [31m│[0m
[31m│[0m   [2m360 [0m[2m│   [0m                                                                   [31m│[0m
[31m│[0m   [2m361 [0m[2m│   [0m[94mdef[0m[90m [0m[92mget_extra_info[0m([96mself[0m, name, default=[94mNone[0m):                      [31m│[0m
[31m│[0m   [2m362 [0m[2m│   │   [0m[94mreturn[0m [96mself[0m._transport.get_extra_info(name, default)           [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/venv/lib/python3.9/site-packages/meltano/core/logging/[0m[1mutils.py[0m:271 in       [31m│[0m
[31m│[0m _write_line_writer                                                           [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m268 [0m[2m│   [0m[94mif[0m [96misinstance[0m(writer, asyncio.StreamWriter):                       [31m│[0m
[31m│[0m   [2m269 [0m[2m│   │   [0m[94mtry[0m:                                                           [31m│[0m
[31m│[0m   [2m270 [0m[2m│   │   │   [0mwriter.write(line)                                         [31m│[0m
[31m│[0m [31m❱ [0m271 [2m│   │   │   [0m[94mawait[0m writer.drain()                                       [31m│[0m
[31m│[0m   [2m272 [0m[2m│   │   [0m[94mexcept[0m ([96mBrokenPipeError[0m, [96mConnectionResetError[0m):                [31m│[0m
[31m│[0m   [2m273 [0m[2m│   │   │   [0m[94mawait[0m writer.wait_closed()                                 [31m│[0m
[31m│[0m   [2m274 [0m[2m│   │   │   [0m[94mreturn[0m [94mFalse[0m                                               [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/usr/local/lib/python3.9/asyncio/[0m[1mstreams.py[0m:387 in drain                     [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m384 [0m[2m│   │   │   [0m[2m# in a loop would never call connection_lost(), so it[0m      [31m│[0m
[31m│[0m   [2m385 [0m[2m│   │   │   [0m[2m# would not see an error when the socket is closed.[0m        [31m│[0m
[31m│[0m   [2m386 [0m[2m│   │   │   [0m[94mawait[0m sleep([94m0[0m)                                             [31m│[0m
[31m│[0m [31m❱ [0m387 [2m│   │   [0m[94mawait[0m [96mself[0m._protocol._drain_helper()                           [31m│[0m
[31m│[0m   [2m388 [0m                                                                       [31m│[0m
[31m│[0m   [2m389 [0m                                                                       [31m│[0m
[31m│[0m   [2m390 [0m[94mclass[0m[90m [0m[4;92mStreamReader[0m:                                                    [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m [2m/usr/local/lib/python3.9/asyncio/[0m[1mstreams.py[0m:197 in _drain_helper             [31m│[0m
[31m│[0m                                                                              [31m│[0m
[31m│[0m   [2m194 [0m[2m│   │   [0m[94massert[0m waiter [95mis[0m [94mNone[0m [95mor[0m waiter.cancelled()                    [31m│[0m
[31m│[0m   [2m195 [0m[2m│   │   [0mwaiter = [96mself[0m._loop.create_future()                            [31m│[0m
[31m│[0m   [2m196 [0m[2m│   │   [0m[96mself[0m._drain_waiter = waiter                                    [31m│[0m
[31m│[0m [31m❱ [0m197 [2m│   │   [0m[94mawait[0m waiter                                                   [31m│[0m
[31m│[0m   [2m198 [0m[2m│   [0m                                                                   [31m│[0m
[31m│[0m   [2m199 [0m[2m│   [0m[94mdef[0m[90m [0m[92m_get_close_waiter[0m([96mself[0m, stream):                               [31m│[0m
[31m│[0m   [2m200 [0m[2m│   │   [0m[94mraise[0m [96mNotImplementedError[0m                                      [31m│[0m
[31m╰──────────────────────────────────────────────────────────────────────────────╯[0m
[1;91mBrokenPipeError[0m
[2025-07-09T20:51:54.400+0000] {docker.py:429} INFO - Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to
join our friendly Slack community.
[2025-07-09T20:51:55.539+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 502, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 376, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 437, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-07-09T20:51:55.548+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=northwind, task_id=carregamento_postgres, execution_date=20250709T204538, start_date=20250709T205139, end_date=20250709T205155
[2025-07-09T20:51:55.632+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2025-07-09T20:51:55.633+0000] {configuration.py:1046} WARNING - section/key [smtp/smtp_user] not found in config
[2025-07-09T20:51:55.634+0000] {email.py:270} INFO - Email alerting: attempt 1
[2025-07-09T20:51:55.646+0000] {configuration.py:1046} WARNING - section/key [smtp/smtp_user] not found in config
[2025-07-09T20:51:55.647+0000] {email.py:270} INFO - Email alerting: attempt 1
[2025-07-09T20:51:55.648+0000] {taskinstance.py:826} ERROR - Failed to send email to: ['lrbf@cin.ufpe.br']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2334, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2499, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2516, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 502, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 376, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/docker/operators/docker.py", line 437, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1000, in _email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.10/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.10/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/local/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 824, in _handle_failure
    task_instance.email_alert(error, failure_context["task"])
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2946, in email_alert
    _email_alert(task_instance=self, exception=exception, task=task)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1002, in _email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.10/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.10/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/local/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[2025-07-09T20:51:55.679+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 97 for task carregamento_postgres (Docker container failed: {'StatusCode': 1}; 213)
[2025-07-09T20:51:55.721+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-09T20:51:55.761+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
